#debug: true
custom:
  kafka:
    topics:
      stats: stats
      linear-acceleration: linear_acceleration
      accelerometer: accelerometer
      gyroscope: gyroscope
      light: light
      user-ids: user-ids

spring:
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
      roles: ADMINISTRATOR
  cloud:
    stream:
      bindings:
        input:
          contentType: application/*+avro
          consumer:
            useNativeDecoding: true
        output:
          producer:
            useNativeEncoding: true
        # Configure the bindings
        linear-acceleration:
          destination: ${custom.kafka.topics.linear-acceleration}
        accelerometer:
          destination: ${custom.kafka.topics.accelerometer}
        gyroscope:
          destination: ${custom.kafka.topics.gyroscope}
        light:
          destination: ${custom.kafka.topics.light}
        stats:
          destination: ${custom.kafka.topics.stats}
        user-ids-in:
          destination: ${custom.kafka.topics.user-ids}

      # Native Encoding enables the kafka serialization/deserialization
      default.producer:
        useNativeEncoding: true
      default.consumer:
        useNativeEncoding: true

      kafka:
        streams:
          # Configure the kafka streams binder to consume messages
          binder:
            brokers: kafka:29092
            configuration:
              # TODO: use native encoding (is it used already?)
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              schema.registry.url: http://schema-registry:8081
              cache.max.bytes.buffering: 0
          bindings:
            linear-acceleration:
              consumer:
                application-id: indicator-linear-acceleration
            accelerometer:
              consumer:
                application-id: indicator-accelerometer
            gyroscope:
              consumer:
                application-id: indicator-gyroscope
            light:
              consumer:
                application-id: indicator-light
            stats:
              consumer:
                application-id: indicator-stats
            user-ids-in:
              consumer:
                keySerde: io.confluent.kafka.streams.serdes.avro.PrimitiveAvroSerde
                application-id: indicator-user-ids-in

